<a href="https://colab.research.google.com/github/Arif118/Crop-Recommendation/blob/main/Crop_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import joblib
#import matplotlib.pyplot as plt
#import seaborn as sns

In [4]:
df = pd.read_csv('Crop_recommendation.xls')
df = pd.DataFrame(df)
df.sample(5)

        N    P    K  temperature   humidity        ph    rainfall        label
1466  111   15   54    27.705837  92.911857  6.194090   22.062072    muskmelon
330    17   77   23    24.513248  20.815276  5.670063   64.194979  kidneybeans
90     93   53   38    26.929951  81.914112  7.069172  290.679378         rice
1905  126   50   19    24.694571  81.735888  6.628723   78.584944       cotton
1590   35  131  203    22.427761  93.917224  5.893491  102.723074        apple

In [5]:
df.shape

(2200, 8)

In [6]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [7]:
labels = df['label'].unique()

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

In [9]:
df.sample(5)

        N    P    K  temperature   humidity        ph    rainfall  label
1549   19  122  202    23.344674  90.379815  5.811975  112.895402      0
2030   69   57   35    24.307486  78.543410  6.186814  186.233757      8
415    40   62   19    27.321989  34.137371  4.697751   96.515240     18
1950  140   40   17    22.727672  77.075981  6.006086   77.551763      6
513    24   38   22    24.478765  58.516639  8.202706   34.969333     13

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.2, random_state=42)
#x_test

In [12]:
model = RandomForestClassifier(n_estimators=75, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=75, random_state=42)

In [13]:
model.score(x_test, y_test)

0.9931818181818182

In [14]:
model.feature_importances_

array([0.10931225, 0.14289148, 0.18103484, 0.07579999, 0.21147856,
       0.05164419, 0.22783869])

In [15]:
#prediction = model.predict(x_test)
#prediction

In [16]:
#prediction_x = model.predict([[92,45,36,38,77,6.2,87]])
#labels[prediction_x][0]

In [17]:
joblib.dump(model, "Crop_Recommendation_System.pkl")

['Crop_Recommendation_System.pkl']

In [18]:
user_input = input('Enter values (N,P,K,temp,hum,ph,rain): ')
inp_data = [[float(i) for i in user_input.split(',')]]
print(f'Recommended crop: {le.inverse_transform(model.predict(inp_data))[0]}')

Enter values (N,P,K,temp,hum,ph,rain): 32,45,64,23,53,7.7,89
Recommended crop: mango

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(